### ISSUE TITLE
nothing on Release

### ISSUE THREAD

**Issue by alittlebitofit** [vancha/meme_recreation_coding_challenge#1]
😦

**Comment by alittlebitofit** [comment]
![Screenshot_20220317-165757_Firefox](https://user-images.githubusercontent.com/42311431/158799452-ca5e522c-c8b7-4df7-8ede-cbcc0432a0c8.jpg)

the `Release` section is empty

**Comment by vancha** [comment]
How do i set the state of this bug to "wont fix"...

**Comment by alittlebitofit** [comment]
:o
